name: 'Sphinx Build'
description: 'Builds documentation using Sphinx'
author: 'iterate GmbH, Ammar Askar'
branding:
  icon: 'book'
  color: 'yellow'
inputs:
  docs-folder:
    description:
      The folder containing your sphinx docs.
    required: true
    default: "docs/"
  build-command:
    description:
      The command used to build your documentation.
    required: false
    default: make html
  pre-build-command:
    description:
      Run before the build command, you can use this to install system level
      dependencies, for example with
      "apk add --no-cache perl"
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/iterate-ch/sphinx-action'
